# Generated by Django 4.0.4 on 2022-05-05 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angajati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_familie', models.CharField(max_length=255)),
                ('prenume', models.CharField(max_length=255)),
                ('salariu', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('data_angajare', models.DateField()),
                ('data_nasterii', models.DateField()),
                ('loc_munca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tabele.locurimunca')),
            ],
            options={
                'verbose_name': 'Angajat',
                'verbose_name_plural': 'Angajati',
            },
        ),
    ]
