# Generated by Django 4.0.4 on 2022-05-10 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabele', '0003_adrese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angajati',
            name='loc_munca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tabele.locurimunca'),
        ),
    ]
