# Generated by Django 4.0.4 on 2022-05-11 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabele', '0010_alter_modele_masini_cod_motor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piesa_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originala', models.CharField(choices=[('originala', 'originala'), ('compatibila', 'compatibila')], default='originala', help_text='Alegeti daca piesa este originala sau nu.', max_length=20)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tabele.modele_masini')),
                ('piesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tabele.piese')),
            ],
            options={
                'verbose_name': 'Legatura Piesa - Model',
                'verbose_name_plural': 'Legaturi Piesa - Model',
            },
        ),
    ]
