# Generated by Django 4.0.4 on 2022-05-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabele', '0011_piesa_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masini',
            fields=[
                ('vin', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('nr_inmatriculare', models.CharField(max_length=10)),
                ('an_fabricatie', models.PositiveSmallIntegerField()),
                ('kilometraj', models.CharField(default='0', max_length=9)),
            ],
            options={
                'verbose_name': 'Masina',
                'verbose_name_plural': 'Masini',
            },
        ),
    ]
