from django.urls import path
from . import views
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='home/', permanent=True)),
    path('home/', views.home, name='home'),
    path('create/', views.create, name='create'),
    path('create/locmunca', views.create_LocMunca, name='create_locmunca'),
    path('create/anagajati', views.create_Angajat, name='create_angajat'),
    path('create/clienti', views.create_Client, name='create_client'),
    path('create/modele', views.create_Model, name='create_model'),
    path('create/piese', views.create_Piesa, name='create_piesa'),
    path('create/piesamodel', views.create_PiesaModel, name='create_piesamodel'),
    path('create/masina', views.create_Masina, name='create_masina'),
    path('create/comanda', views.create_Comanda, name='create_comanda'),
    path('create/comandapiesa', views.create_ComandaPiesa, name='create_comandapiesa'),
    path('search/', views.search, name='search'),
    path('search/locurimunca', views.read_LocuriMunca, name='search_locurimunca'),
    path('search/angajati', views.read_Angajati, name='search_angajati'),
    path('search/clienti', views.read_Clienti, name='search_clienti'),
    path('search/modele', views.read_Modele, name='search_modele'),
    path('search/piese', views.read_Piese, name='search_piese'),
    path('search/piesamodel', views.read_PiesaModel, name='search_piesamodel'),
    path('search/masini', views.read_Masini, name='search_masini'),
    path('search/comenzi', views.read_Comenzi, name='search_comenzi'),
    path('search/comandapiesa', views.read_ComandaPiesa, name='search_comandapiesa'),
    path('update/locurimunca/<int:pk>', views.update_LocuriMunca, name='update_locurimunca'),
    path('update/angajati/<int:pk>', views.update_Angajati, name='update_locurimunca'),
    path('update/clienti/<int:pk>', views.update_Clienti, name='update_clienti'),
    path('update/modele/<int:pk>', views.update_Modele, name='update_modele'),
    path('update/piese/<int:pk>', views.update_Piese, name='update_piese'),
    path('update/piesamodel/<int:pk>', views.update_PiesaModel, name='update_piesamodel'),
    path('update/masini/<int:pk>', views.update_Masini, name='update_masini'),
    path('update/comenzi/<int:pk>', views.update_Comenzi, name='update_comenzi'),
    path('update/comandapiesa/<int:pk>', views.update_ComandaPiesa, name='update_comandapiesa'),
    path('delete/locurimunca/<int:pk>', views.delete_LocuriMunca, name='delete_locurimunca'),
    path('delete/angajati/<int:pk>', views.delete_Angajati, name='delete_angajati'),
    path('delete/clienti/<int:pk>', views.delete_Clienti, name='delete_clienti'),
    path('delete/modele/<int:pk>', views.delete_Modele, name='delete_modele'),
    path('delete/piese/<int:pk>', views.delete_Piese, name='delete_piese'),
    path('delete/piesamodel/<int:pk>', views.delete_PiesaModel, name='delete_piesamodel'),
    path('delete/masini/<int:pk>', views.delete_Masini, name='delete_masini'),
    path('delete/comenzi/<int:pk>', views.delete_Comenzi, name='delete_comenzi'),
    path('delete/comandapiesa/<int:pk>', views.delete_ComandaPiesa, name='delete_comandapiesa'),
    # path('search/', views.search, name='search'),
    # path('update/<int:pk>', views.update, name='update'),
    # path('delete/<int:pk>', views.delete, name='delete'),
]