# Generated by Django 4.0.4 on 2022-05-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocuriMunca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=255)),
                ('salariu_min', models.IntegerField()),
                ('salariu_max', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Loc munca',
                'verbose_name_plural': 'Locuri munca',
            },
        ),
    ]
