# Generated by Django 4.0.4 on 2022-05-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabele', '0007_modele_masini'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=255)),
                ('producator', models.CharField(max_length=255)),
                ('interval_recomandat_schimb', models.CharField(max_length=255)),
                ('data_fabricatie', models.DateField()),
                ('pret_ron', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Piesa',
                'verbose_name_plural': 'Piese',
            },
        ),
        migrations.AlterModelOptions(
            name='clienti',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clienti'},
        ),
        migrations.AlterModelOptions(
            name='modele_masini',
            options={'verbose_name': 'Model Masina', 'verbose_name_plural': 'Modele Masini'},
        ),
        migrations.AlterField(
            model_name='modele_masini',
            name='cod_motor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modele_masini',
            name='motorizare_cc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
