# Generated by Django 4.0.4 on 2022-05-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabele', '0009_remove_piese_data_fabricatie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modele_masini',
            name='cod_motor',
            field=models.CharField(default='Nu exista', max_length=255),
        ),
        migrations.AlterField(
            model_name='modele_masini',
            name='motorizare_cc',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='piese',
            name='interval_recomandat_schimb',
            field=models.CharField(default='nu exista', max_length=255),
        ),
    ]
