# Generated by Django 4.0.4 on 2022-05-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabele', '0013_comenzi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comenzi',
            old_name='angajat_id',
            new_name='angajat_nume',
        ),
        migrations.RenameField(
            model_name='comenzi',
            old_name='client_cnp',
            new_name='client_nume',
        ),
        migrations.RenameField(
            model_name='comenzi',
            old_name='masina_vin',
            new_name='masina_nr',
        ),
    ]
