# Generated by Django 4.0.4 on 2022-05-12 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabele', '0014_rename_angajat_id_comenzi_angajat_nume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComandaPiesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_piese', models.IntegerField()),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tabele.comenzi')),
                ('piesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tabele.piese')),
            ],
            options={
                'verbose_name': 'Legatura Comanda - Piesa',
                'verbose_name_plural': 'Legaturi Comenzi - Piese',
            },
        ),
    ]
