# Generated by Django 4.0.4 on 2022-05-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabele', '0015_comandapiesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adrese',
            name='apartament',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='adrese',
            name='etaj',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='adrese',
            name='nr_bloc',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='adrese',
            name='nr_strada',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='adrese',
            name='scara',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='comandapiesa',
            name='nr_piese',
            field=models.IntegerField(default='1'),
        ),
    ]
