# Generated by Django 4.0.4 on 2022-05-12 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabele', '0016_alter_adrese_apartament_alter_adrese_etaj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livrari',
            fields=[
                ('awb', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status_livrare', models.CharField(choices=[('primita', 'primita'), ('in curs de livrare', 'in curs de livrare'), ('livrata', 'livrata')], default='primita', max_length=30)),
                ('data_programata_livrare', models.DateField()),
                ('adresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tabele.adrese')),
                ('angajat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tabele.angajati')),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tabele.comenzi')),
            ],
            options={
                'verbose_name': 'Livrare',
                'verbose_name_plural': 'Livrari',
            },
        ),
    ]
