# Generated by Django 4.0.4 on 2022-05-13 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabele', '0017_livrari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angajati',
            name='loc_munca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tabele.locurimunca'),
        ),
        migrations.AlterField(
            model_name='comandapiesa',
            name='comanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabele.comenzi'),
        ),
        migrations.AlterField(
            model_name='comandapiesa',
            name='piesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabele.piese'),
        ),
        migrations.AlterField(
            model_name='comenzi',
            name='angajat_nume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tabele.angajati'),
        ),
        migrations.AlterField(
            model_name='comenzi',
            name='client_nume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tabele.clienti'),
        ),
        migrations.AlterField(
            model_name='comenzi',
            name='masina_nr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tabele.masini'),
        ),
        migrations.AlterField(
            model_name='livrari',
            name='adresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tabele.adrese'),
        ),
        migrations.AlterField(
            model_name='livrari',
            name='angajat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tabele.angajati'),
        ),
        migrations.AlterField(
            model_name='livrari',
            name='comanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabele.comenzi'),
        ),
        migrations.AlterField(
            model_name='piesa_model',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabele.modele_masini'),
        ),
        migrations.AlterField(
            model_name='piesa_model',
            name='piesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabele.piese'),
        ),
    ]
