# Generated by Django 4.0.4 on 2022-05-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabele', '0018_alter_angajati_loc_munca_alter_comandapiesa_comanda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livrari',
            name='awb',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
